// Generated by gencpp from file robot_msgs/cambiar_vel.msg
// DO NOT EDIT!


#ifndef ROBOT_MSGS_MESSAGE_CAMBIAR_VEL_H
#define ROBOT_MSGS_MESSAGE_CAMBIAR_VEL_H

#include <ros/service_traits.h>


#include <robot_msgs/cambiar_velRequest.h>
#include <robot_msgs/cambiar_velResponse.h>


namespace robot_msgs
{

struct cambiar_vel
{

typedef cambiar_velRequest Request;
typedef cambiar_velResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct cambiar_vel
} // namespace robot_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_msgs::cambiar_vel > {
  static const char* value()
  {
    return "8741f5a26630d67b17b5a382a1c74988";
  }

  static const char* value(const ::robot_msgs::cambiar_vel&) { return value(); }
};

template<>
struct DataType< ::robot_msgs::cambiar_vel > {
  static const char* value()
  {
    return "robot_msgs/cambiar_vel";
  }

  static const char* value(const ::robot_msgs::cambiar_vel&) { return value(); }
};


// service_traits::MD5Sum< ::robot_msgs::cambiar_velRequest> should match
// service_traits::MD5Sum< ::robot_msgs::cambiar_vel >
template<>
struct MD5Sum< ::robot_msgs::cambiar_velRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_msgs::cambiar_vel >::value();
  }
  static const char* value(const ::robot_msgs::cambiar_velRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_msgs::cambiar_velRequest> should match
// service_traits::DataType< ::robot_msgs::cambiar_vel >
template<>
struct DataType< ::robot_msgs::cambiar_velRequest>
{
  static const char* value()
  {
    return DataType< ::robot_msgs::cambiar_vel >::value();
  }
  static const char* value(const ::robot_msgs::cambiar_velRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_msgs::cambiar_velResponse> should match
// service_traits::MD5Sum< ::robot_msgs::cambiar_vel >
template<>
struct MD5Sum< ::robot_msgs::cambiar_velResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_msgs::cambiar_vel >::value();
  }
  static const char* value(const ::robot_msgs::cambiar_velResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_msgs::cambiar_velResponse> should match
// service_traits::DataType< ::robot_msgs::cambiar_vel >
template<>
struct DataType< ::robot_msgs::cambiar_velResponse>
{
  static const char* value()
  {
    return DataType< ::robot_msgs::cambiar_vel >::value();
  }
  static const char* value(const ::robot_msgs::cambiar_velResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_MSGS_MESSAGE_CAMBIAR_VEL_H
