// Generated by gencpp from file robot_msgs/cambiar_velRequest.msg
// DO NOT EDIT!


#ifndef ROBOT_MSGS_MESSAGE_CAMBIAR_VELREQUEST_H
#define ROBOT_MSGS_MESSAGE_CAMBIAR_VELREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_msgs
{
template <class ContainerAllocator>
struct cambiar_velRequest_
{
  typedef cambiar_velRequest_<ContainerAllocator> Type;

  cambiar_velRequest_()
    : velocidad(0.0)  {
    }
  cambiar_velRequest_(const ContainerAllocator& _alloc)
    : velocidad(0.0)  {
  (void)_alloc;
    }



   typedef float _velocidad_type;
  _velocidad_type velocidad;





  typedef boost::shared_ptr< ::robot_msgs::cambiar_velRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_msgs::cambiar_velRequest_<ContainerAllocator> const> ConstPtr;

}; // struct cambiar_velRequest_

typedef ::robot_msgs::cambiar_velRequest_<std::allocator<void> > cambiar_velRequest;

typedef boost::shared_ptr< ::robot_msgs::cambiar_velRequest > cambiar_velRequestPtr;
typedef boost::shared_ptr< ::robot_msgs::cambiar_velRequest const> cambiar_velRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_msgs::cambiar_velRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_msgs::cambiar_velRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_msgs::cambiar_velRequest_<ContainerAllocator1> & lhs, const ::robot_msgs::cambiar_velRequest_<ContainerAllocator2> & rhs)
{
  return lhs.velocidad == rhs.velocidad;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_msgs::cambiar_velRequest_<ContainerAllocator1> & lhs, const ::robot_msgs::cambiar_velRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::cambiar_velRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::cambiar_velRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::cambiar_velRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::cambiar_velRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::cambiar_velRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::cambiar_velRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_msgs::cambiar_velRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "038d1d82280753495fded4897c712e65";
  }

  static const char* value(const ::robot_msgs::cambiar_velRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x038d1d8228075349ULL;
  static const uint64_t static_value2 = 0x5fded4897c712e65ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_msgs::cambiar_velRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_msgs/cambiar_velRequest";
  }

  static const char* value(const ::robot_msgs::cambiar_velRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_msgs::cambiar_velRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 velocidad\n"
;
  }

  static const char* value(const ::robot_msgs::cambiar_velRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_msgs::cambiar_velRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.velocidad);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct cambiar_velRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_msgs::cambiar_velRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_msgs::cambiar_velRequest_<ContainerAllocator>& v)
  {
    s << indent << "velocidad: ";
    Printer<float>::stream(s, indent + "  ", v.velocidad);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_MSGS_MESSAGE_CAMBIAR_VELREQUEST_H
