// Generated by gencpp from file robot_msgs/cambiar_velResponse.msg
// DO NOT EDIT!


#ifndef ROBOT_MSGS_MESSAGE_CAMBIAR_VELRESPONSE_H
#define ROBOT_MSGS_MESSAGE_CAMBIAR_VELRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_msgs
{
template <class ContainerAllocator>
struct cambiar_velResponse_
{
  typedef cambiar_velResponse_<ContainerAllocator> Type;

  cambiar_velResponse_()
    : Mensaje()  {
    }
  cambiar_velResponse_(const ContainerAllocator& _alloc)
    : Mensaje(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _Mensaje_type;
  _Mensaje_type Mensaje;





  typedef boost::shared_ptr< ::robot_msgs::cambiar_velResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_msgs::cambiar_velResponse_<ContainerAllocator> const> ConstPtr;

}; // struct cambiar_velResponse_

typedef ::robot_msgs::cambiar_velResponse_<std::allocator<void> > cambiar_velResponse;

typedef boost::shared_ptr< ::robot_msgs::cambiar_velResponse > cambiar_velResponsePtr;
typedef boost::shared_ptr< ::robot_msgs::cambiar_velResponse const> cambiar_velResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_msgs::cambiar_velResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_msgs::cambiar_velResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_msgs::cambiar_velResponse_<ContainerAllocator1> & lhs, const ::robot_msgs::cambiar_velResponse_<ContainerAllocator2> & rhs)
{
  return lhs.Mensaje == rhs.Mensaje;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_msgs::cambiar_velResponse_<ContainerAllocator1> & lhs, const ::robot_msgs::cambiar_velResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::cambiar_velResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::cambiar_velResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::cambiar_velResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::cambiar_velResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::cambiar_velResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::cambiar_velResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_msgs::cambiar_velResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e238a58a5f2dd3b7d0de288ab5ff05c0";
  }

  static const char* value(const ::robot_msgs::cambiar_velResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe238a58a5f2dd3b7ULL;
  static const uint64_t static_value2 = 0xd0de288ab5ff05c0ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_msgs::cambiar_velResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_msgs/cambiar_velResponse";
  }

  static const char* value(const ::robot_msgs::cambiar_velResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_msgs::cambiar_velResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string Mensaje\n"
"\n"
"\n"
"\n"
;
  }

  static const char* value(const ::robot_msgs::cambiar_velResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_msgs::cambiar_velResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Mensaje);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct cambiar_velResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_msgs::cambiar_velResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_msgs::cambiar_velResponse_<ContainerAllocator>& v)
  {
    s << indent << "Mensaje: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.Mensaje);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_MSGS_MESSAGE_CAMBIAR_VELRESPONSE_H
