// Generated by gencpp from file robot_msgs/ultrasonico.msg
// DO NOT EDIT!


#ifndef ROBOT_MSGS_MESSAGE_ULTRASONICO_H
#define ROBOT_MSGS_MESSAGE_ULTRASONICO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Bool.h>
#include <sensor_msgs/Range.h>

namespace robot_msgs
{
template <class ContainerAllocator>
struct ultrasonico_
{
  typedef ultrasonico_<ContainerAllocator> Type;

  ultrasonico_()
    : metrico()
    , ultrasonico()  {
    }
  ultrasonico_(const ContainerAllocator& _alloc)
    : metrico(_alloc)
    , ultrasonico(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Bool_<ContainerAllocator>  _metrico_type;
  _metrico_type metrico;

   typedef  ::sensor_msgs::Range_<ContainerAllocator>  _ultrasonico_type;
  _ultrasonico_type ultrasonico;





  typedef boost::shared_ptr< ::robot_msgs::ultrasonico_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_msgs::ultrasonico_<ContainerAllocator> const> ConstPtr;

}; // struct ultrasonico_

typedef ::robot_msgs::ultrasonico_<std::allocator<void> > ultrasonico;

typedef boost::shared_ptr< ::robot_msgs::ultrasonico > ultrasonicoPtr;
typedef boost::shared_ptr< ::robot_msgs::ultrasonico const> ultrasonicoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_msgs::ultrasonico_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_msgs::ultrasonico_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_msgs::ultrasonico_<ContainerAllocator1> & lhs, const ::robot_msgs::ultrasonico_<ContainerAllocator2> & rhs)
{
  return lhs.metrico == rhs.metrico &&
    lhs.ultrasonico == rhs.ultrasonico;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_msgs::ultrasonico_<ContainerAllocator1> & lhs, const ::robot_msgs::ultrasonico_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::ultrasonico_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::ultrasonico_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::ultrasonico_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::ultrasonico_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::ultrasonico_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::ultrasonico_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_msgs::ultrasonico_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4d215fc6d958a6fc2548282e53b7769e";
  }

  static const char* value(const ::robot_msgs::ultrasonico_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4d215fc6d958a6fcULL;
  static const uint64_t static_value2 = 0x2548282e53b7769eULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_msgs::ultrasonico_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_msgs/ultrasonico";
  }

  static const char* value(const ::robot_msgs::ultrasonico_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_msgs::ultrasonico_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Bool metrico\n"
"sensor_msgs/Range ultrasonico\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Bool\n"
"bool data\n"
"================================================================================\n"
"MSG: sensor_msgs/Range\n"
"# Single range reading from an active ranger that emits energy and reports\n"
"# one range reading that is valid along an arc at the distance measured. \n"
"# This message is  not appropriate for laser scanners. See the LaserScan\n"
"# message if you are working with a laser scanner.\n"
"\n"
"# This message also can represent a fixed-distance (binary) ranger.  This\n"
"# sensor will have min_range===max_range===distance of detection.\n"
"# These sensors follow REP 117 and will output -Inf if the object is detected\n"
"# and +Inf if the object is outside of the detection range.\n"
"\n"
"Header header           # timestamp in the header is the time the ranger\n"
"                        # returned the distance reading\n"
"\n"
"# Radiation type enums\n"
"# If you want a value added to this list, send an email to the ros-users list\n"
"uint8 ULTRASOUND=0\n"
"uint8 INFRARED=1\n"
"\n"
"uint8 radiation_type    # the type of radiation used by the sensor\n"
"                        # (sound, IR, etc) [enum]\n"
"\n"
"float32 field_of_view   # the size of the arc that the distance reading is\n"
"                        # valid for [rad]\n"
"                        # the object causing the range reading may have\n"
"                        # been anywhere within -field_of_view/2 and\n"
"                        # field_of_view/2 at the measured range. \n"
"                        # 0 angle corresponds to the x-axis of the sensor.\n"
"\n"
"float32 min_range       # minimum range value [m]\n"
"float32 max_range       # maximum range value [m]\n"
"                        # Fixed distance rangers require min_range==max_range\n"
"\n"
"float32 range           # range data [m]\n"
"                        # (Note: values < range_min or > range_max\n"
"                        # should be discarded)\n"
"                        # Fixed distance rangers only output -Inf or +Inf.\n"
"                        # -Inf represents a detection within fixed distance.\n"
"                        # (Detection too close to the sensor to quantify)\n"
"                        # +Inf represents no detection within the fixed distance.\n"
"                        # (Object out of range)\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::robot_msgs::ultrasonico_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_msgs::ultrasonico_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.metrico);
      stream.next(m.ultrasonico);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ultrasonico_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_msgs::ultrasonico_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_msgs::ultrasonico_<ContainerAllocator>& v)
  {
    s << indent << "metrico: ";
    s << std::endl;
    Printer< ::std_msgs::Bool_<ContainerAllocator> >::stream(s, indent + "  ", v.metrico);
    s << indent << "ultrasonico: ";
    s << std::endl;
    Printer< ::sensor_msgs::Range_<ContainerAllocator> >::stream(s, indent + "  ", v.ultrasonico);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_MSGS_MESSAGE_ULTRASONICO_H
